### ISSUE TITLE
Google not responding with provider in response QPs. Always ending in bad state

### ISSUE THREAD

**Issue by bcardarella** [Erlang-Openid/oidcc_cowboy#14]
The return URL I get from Google is: http://localhost:4000/session?code=4/D7X-sLvBXgnr0AvHQUg7eZElYne3Wxli6xcpHr36Bts&authuser=0&session_state=c3ea9014627930999c2db4d3e8ba16dbb04dd4c6..2b18&prompt=consent# which does not include a `provider` params. According to: https://github.com/indigo-dc/oidcc_cowboy/blob/master/src/oidcc_cowboy.erl#L269 `oidcc_cowboy` requires the `provider` param to create a new session.

I've looked through the Google' API console but cannot find any option to include this.

**Comment by bcardarella** [comment]
Is this relevant? https://github.com/indigo-dc/oidcc_cowboy/blob/436f0d38e3d1c5a864696976c4836cc43aa98dd0/example/basic_client/priv/templates/basic_client.dtl#L8

**Comment by bwegh** [comment]
sorry, I totally missed this entry.
that return is correct, the provider Id is only needed when starting the redirection, not when coming back.

when returning from a provider, like with your url the relevant code is:
https://github.com/indigo-dc/oidcc_cowboy/blob/master/src/oidcc_cowboy.erl#L270 and following, the `undefined` case.

what is the error you receive?

**Comment by maennchen** [comment]
No longer relevant with `v2`.

The provider now has to be specified per `cowboy_handler` therefore it needs to be added multiple times for multiple providers.
